TIPE DATA

In [ ]:
A = 30
print(A)
print(type(A))

30
<class 'int'>


In [ ]:
B = 0.25
print (B)
print(type(B))

0.25
<class 'float'>


In [ ]:
contoh_dictionary = {'nama':'sicle' , 'nim':'1234'}
print(contoh_dictionary)
print(type(contoh_dictionary))

{'nama': 'sicle', 'nim': '1234'}
<class 'dict'>


In [ ]:
print(contoh_dictionary.keys())

dict_keys(['nama', 'nim'])


In [ ]:
print(contoh_dictionary.values())

dict_values(['sicle', '1234'])


In [ ]:
kondisi = 10 < 0
kondisi2 = 10 > 0
print(kondisi)
print(kondisi2)

False
True


In [ ]:
contoh_set = {1,2,3,'a','b','c'}
print(contoh_set)
print(type(contoh_set))

{1, 2, 3, 'a', 'c', 'b'}
<class 'set'>


In [ ]:
contoh_list = ['aku', 1, 2]
print(contoh_list)
print(type(contoh_list))

['aku', 1, 2]
<class 'list'>


In [ ]:
contoh_tuple = ('aku', 1, 2)
print(contoh_tuple)
print(type(contoh_tuple))

('aku', 1, 2)
<class 'tuple'>


In [ ]:
kata = "Aku anak Sircle"
print(kata)
print(type(kata))

Aku anak Sircle
<class 'str'>


OPERATOR ARITMATIKA

In [ ]:
A = 5
B = 2
hasil = A // B #+,-,/,*,%,**,//
print (hasil)

2


OPERATOR PERBANDINGAN


In [ ]:
cek = A <= B # ==, != , < , > , <= , >=
print(cek)

False


OPERASI PENUGASAN

In [ ]:
angka = 5
angka += 2 # angka = angka + 2 , -= , *=, /=, **=, //=, %=
print(angka)

2.5


OPERASI LOGIKA

In [ ]:
T = True
F = False
print (T and F) 
print (T or F)

False
True


CONTROL FLOW

In [ ]:
angka1 = 0
if angka1 > 0:
  print("bilangan positif")
elif angka1 < 0:
  print("bilangan negatif")
else :
  print("bernilai 0")

bernilai 0


ITERATIVE STATEMENT

In [ ]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for a in range(10, 40, 5):
    print(a)

10
15
20
25
30
35


In [ ]:
angka = 0
while angka < 5:
    print("hallo", angka)
    angka += 1


hallo 0
hallo 1
hallo 2
hallo 3
hallo 4


TRANSFER STATEMENTS

In [ ]:
for b in range(1, 11):
    print(b)
    if b is 5:
        print("Angka ditemukan ", b)
        break  # keluar dari proses looping

1
2
3
4
5
Angka ditemukan  5


In [ ]:
for number in range(10):
    if number == 5:
        continue    # continue here

    print('Angka ' + str(number))

Angka 0
Angka 1
Angka 2
Angka 3
Angka 4
Angka 6
Angka 7
Angka 8
Angka 9


In [ ]:
for number in range(10):
    if number == 5:
        pass    # ada tpi ga ada, tidak memiliki tugas apapun

    print('Number is ' + str(number))

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Number is 5
Number is 6
Number is 7
Number is 8
Number is 9


In [ ]:
#contohnya klau kita buat fungsi, tpi kita blm tau isinya tuh apa
def halaman_utama ():
  pass

DATA MANIPULATION

In [ ]:
import numpy as np
# list python
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
hasil = a + b
print(hasil)

# list array
anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([6, 7, 8, 9, 10])
hasil2 = anp + bnp
print(hasil2)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]


In [ ]:
a = np.arange(10)**2  # ** berarti kuadrat
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
# mengambil nilai
print("elemen ke 1 dari a adalah ", a[0])
print("elemen ke 7 dari a adalah ", a[6])
print("elemen terakhir  dari a adalah ", a[-1])

elemen ke 1 dari a adalah  0
elemen ke 7 dari a adalah  36
elemen terakhir  dari a adalah  81


In [ ]:
# slicing
print("elemen dari 1-6 adalah ", a[0:6])
print("elemen ke 4 sampai akhir ", a[3:])
print("elemen dari awal sampai 5 ", a[:5])

elemen dari 1-6 adalah  [ 0  1  4  9 16 25]
elemen ke 4 sampai akhir  [ 9 16 25 36 49 64 81]
elemen dari awal sampai 5  [ 0  1  4  9 16]


In [ ]:
a = np.array(([1, 2],
              [3, 4]))
b = np.ones([2, 1])#matriks 1, 2 baris 1 kolom


print("Matriks a :")
print(a)
print("Matriks b :")
print(b)

Matriks a :
[[1 2]
 [3 4]]
Matriks b :
[[1.]
 [1.]]


In [ ]:
# perkalian matiks
c = np.dot(a, b)
#c2 = a.dot(b)
print("matriks c : ")
print(c)
#print(c2)

matriks c : 
[[3.]
 [7.]]
